### ISSUE TITLE
Basis of program has done

### ISSUE THREAD

**Issue by juenkhaw** [juenkhaw/PCD2-assgmt#3]
Program is now free to insert customer/manager functions
<strong>WE WILL NOT UPDATE ANY OF THE DEPOSIT/WITHDRAWAL FUNCTIONS</strong>
The updates after this will only manipulate the code basis.
CODE ARE FREE TO ADD ON IT BUT TRY TO <strong>NOT MANIPULATE THE PROGRAM BASIS</strong>
but variables needed are free to add on the main.cpp and other files.

**Comment by ZorevGnoz** [comment]
tat juen...
i tried copy and paste ur main function but it cant be run...
ill let u see it tmr
-Veron(20/11/2015)

**Comment by juenkhaw** [comment]
erm i dont think this will be worked on 10 version. It needs at least 13 to compile so far i knew

**Comment by ZorevGnoz** [comment]
damn...lol
btw...how can go back to the menu?
for example...
i click deposit function...then i realized that im in the wrong catergory...i wanna go back to the main function. 
i already put the back to main menu as one of the selection, but what im i suppost to  put so that it can run it back?

do
    {
        check = NULL;
        mainmenu = -1;
        printf("MAIN MENU:\n"
            "1 = Customer Menu\n"
            "2 = Manager Menu\n"
            "3 = End Transaction\n"
            "Your selection : ");
        fflush(stdin);
        scanf("%d%c",&mainmenu,&check);
    } while (mainmenu<1||mainmenu>3||check!='\n');

```
if(mainmenu==1)
{
    do
    {
        check = NULL;
        custmenu = -1;
        printf("\nMAIN MENU > Customer Menu\n"
            "1 = Deposit System\n"
            "2 = Withdrawals / Cash Transfers System\n"
            "3 = Bill Payment System\n"
            "4 = Change Current Password\n"
            "5 = Back to MAIN MENU\n"
            "Your selection : ");
        fflush(stdin);
        scanf("%d%c",&custmenu,&check);
    } while (custmenu<1||custmenu>5||check!='\n');
```
