### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by ZorevGnoz** [juenkhaw/PCD2-assgmt#4]
FILE *c = fopen("Customer.txt", "r+");

```
struct customer cust[20];
for(int i=0;i<20;i++)
{
    while(fscanf(c,"%d|",&cust[i].acc_no) != EOF)
    {

        fscanf(c,"%d|%[^|]|%c|%[^|]|%[^|]|%[^|]|%d|%lf|%d/%d/%d|%d:%d\n",
        &cust[i].pin,&cust[i].name,&cust[i].gender,&cust[i].address,&cust[i].state,
        &cust[i].country,&cust[i].contact_no,&cust[i].acc_bal,
        &cust[i].last_txndate.day,&cust[i].last_txndate.month,&cust[i].last_txndate.year,
        &cust[i].last_txntime.hr,&cust[i].last_txntime.min);
    }
}
```

Any error here? Cuz it seems to keep running,,,

**Comment by ZorevGnoz** [comment]
the first post problem settled dy...

do
    {
        printf("Please type in your account number : ");
        scanf("%d",&accno);
        fflush(stdin);
        for(int j=0;j<20;j++)
        {
            if(accno==cust[j].acc_no)
            {
                do
                {
                    printf("Please type in your account password : ");
                    scanf("%d",&pinno);
                    fflush(stdin);
                    if(pinno==cust[j].pin)
                    {
                        printf("Welcome back %s\n",cust[j].name);
                    }
                }while(pinno!=cust[j].pin);
            }
            else
                printf("Account not found\n");
        }
    }while(accno!=-1);

can run until for loop only..the others cant use...

**Comment by juenkhaw** [comment]
it depends on the format of ur text file, maybe u just use wrong format to
scan ur file
